//---------------------------------------------------------------------------
#ifndef MainH
#define MainH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ActnList.hpp>
#include <Menus.hpp>
#include <Dialogs.hpp>
//---------------------------------------------------------------------------
#include <ExtCtrls.hpp>
#include <ComCtrls.hpp>
#include <ToolWin.hpp>
#include <ImgList.hpp>
//---------------------------------------------------------------------------
#include "QuiltingLib.h"
#include "FormTranslation.h"
#include <AppEvnts.hpp>
#include <ExtDlgs.hpp>
#include "CSPIN.h"
#include <Buttons.hpp>
//---------------------------------------------------------------------------
#include "SystemInfoLib.h"
//---------------------------------------------------------------------------
class TFormMain : public TForm
{
__published:	// IDE-managed Components
	TActionList *ActionList1;
	TMainMenu *MainMenu1;
	TAction *AFile;
	TAction *AFileOpen;
	TAction *AFileSave;
	TAction *AFileSaveAs;
	TAction *AFileExit;
	TMenuItem *File1;
	TMenuItem *Open1;
	TMenuItem *N1;
	TMenuItem *Save1;
	TMenuItem *SaveAs1;
	TMenuItem *Exit1;
	TOpenDialog *OpenDialogDAT;
	TSaveDialog *SaveDialogDAT;
	TPanel *PanelDisplay;
	TControlBar *ControlBar1;
	TToolBar *ToolBar1;
	TToolButton *ToolButton1;
	TToolButton *ToolButton2;
	TToolButton *ToolButton3;
	TImageList *ImageList;
	TAction *AZoom;
	TAction *AZoomAll;
	TAction *AZoomWindow;
	TAction *AZoomIn;
	TAction *AZoomOut;
	TAction *AZoomPanWindow;
	TAction *ZoomToPrev;
	TToolButton *ToolButton4;
	TToolButton *ToolButton5;
	TToolButton *ToolButton6;
	TStatusBar *StatusBar1;
	TToolBar *ToolBar2;
	TToolButton *ToolButton7;
	TToolButton *ToolButton8;
	TToolButton *ToolButton9;
	TAction *AFileNew;
	TToolButton *ToolButton10;
	TMenuItem *New1;
	TMenuItem *Zoom1;
	TMenuItem *ZoomAll1;
	TMenuItem *ZoomWindow1;
	TMenuItem *ZoomIn1;
	TMenuItem *ZoomOut1;
	TMenuItem *PanWindow1;
	TMenuItem *ZoomToPrev1;
	TAction *ASnap;
	TAction *ASnapDlg;
	TAction *ASnapGrid;
	TAction *ASnapPolar;
	TAction *ASnapGrips;
	TAction *ASnapPoint;
	TAction *ASnapNear;
	TAction *ASnapEnd;
	TAction *ASnapMid;
	TAction *ASnapCenter;
	TAction *ASnapPerpendicular;
	TAction *ASnapTangent;
	TToolBar *ToolBar3;
	TToolButton *ToolButton12;
	TToolButton *ToolButton14;
	TToolButton *ToolButton15;
	TToolButton *ToolButton16;
	TToolButton *ToolButton17;
	TToolButton *ToolButton18;
	TToolButton *ToolButton19;
	TToolButton *ToolButton20;
	TToolButton *ToolButton21;
	TMenuItem *Snap1;
	TMenuItem *SnapGrid1;
	TMenuItem *SnapGrips1;
	TMenuItem *SnapPoint1;
	TMenuItem *SnapNear1;
	TMenuItem *SnapEnd1;
	TMenuItem *SnapMid1;
	TMenuItem *SnapCenter1;
	TMenuItem *SnapPerpendicular1;
	TMenuItem *SnapTangent1;
	TAction *AEdit;
	TAction *AEditEntProp;
	TAction *AEditCopy;
	TAction *AEditMove;
	TAction *AEditRotate;
	TAction *AEditScale;
	TAction *AEditMirror;
	TAction *AEditErase;
	TAction *AEditUndo;
	TAction *AEditRedo;
	TAction *AEditCutCB;
	TAction *AEditCopyCB;
	TAction *AEditPasteCB;
	TMenuItem *AEdit1;
	TMenuItem *Undo1;
	TMenuItem *Redo1;
	TMenuItem *N3;
	TMenuItem *CutToCB1;
	TMenuItem *CopyToCB1;
	TMenuItem *PasteFromCB1;
	TMenuItem *N4;
	TMenuItem *Properties1;
	TMenuItem *N5;
	TMenuItem *Copy1;
	TMenuItem *Move1;
	TMenuItem *Rotate1;
	TMenuItem *Scale1;
	TMenuItem *Mirror1;
	TMenuItem *N6;
	TMenuItem *Erase1;
	TToolBar *ToolBar4;
	TToolButton *ToolButton11;
	TToolButton *ToolButton22;
	TToolButton *ToolButton23;
	TToolButton *ToolButton24;
	TToolButton *ToolButton25;
	TToolButton *ToolButton26;
	TToolButton *ToolButton27;
	TToolButton *ToolButton28;
	TToolButton *ToolButton29;
	TToolButton *ToolButton30;
	TToolButton *ToolButton31;
	TToolButton *ToolButton32;
	TToolButton *ToolButton33;
	TToolButton *ToolButton34;
	TToolButton *ToolButton35;
	TToolButton *ToolButton36;
	TAction *AHelp;
	TAction *AHelpContents;
	TAction *AHelpAbout;
	TMenuItem *Help1;
	TMenuItem *Contents1;
	TMenuItem *N7;
	TMenuItem *About1;
	TAction *AFileExport;
	TMenuItem *Export1;
	TMenuItem *N8;
	TAction *AFileImport;
	TMenuItem *ExportQuilting1;
	TToolButton *ToolButton37;
	TToolButton *ToolButton38;
	TToolButton *ToolButton39;
	TPanel *PanelFileList;
	TGroupBox *GroupBox1;
	TListBox *ListBoxOpenedFiles;
	TAction *AFileClose;
	TMenuItem *Close1;
	TMenuItem *N2;
	TPopupMenu *PopupMenuFileList;
	TMenuItem *Close2;
	TToolBar *ToolBar5;
	TToolButton *ToolButton40;
	TAction *ADraw;
	TAction *ADrawPolyline;
	TMenuItem *Draw1;
	TMenuItem *ADrawPolyline1;
	TAction *ADrawArcCSE;
	TAction *ADrawArcSEM;
	TAction *ADrawArcSME;
	TAction *ADrawCircleCR;
	TAction *ADrawCircleCD;
	TAction *ADrawCircle2P;
	TAction *ADrawCircle3P;
	TAction *ADrawEllipse;
	TMenuItem *N9;
	TMenuItem *ArcCSE1;
	TMenuItem *ArcSEM1;
	TMenuItem *ArcSME1;
	TToolButton *ToolButton41;
	TToolButton *ToolButton42;
	TToolButton *ToolButton43;
	TToolButton *ToolButton44;
	TAction *ADrawLine;
	TAction *ADrawRectangle;
	TAction *AEditSetJump;
	TMenuItem *SetJump1;
	TToolButton *ToolButton52;
	TAction *AEditSetNormal;
	TMenuItem *SetNormal1;
	TToolButton *ToolButton53;
	TSaveDialog *SaveDialogQLT;
	TOpenDialog *OpenDialogQLT;
	TAction *ATools;
	TAction *AToolsSimulator;
	TMenuItem *Tools1;
	TMenuItem *Simulator1;
	TAction *AToolsNavigator;
	TMenuItem *Navigator1;
	TFormTranslation *FormTranslation1;
	TTimer *Timer0;
	TTimer *Timer1;
	TTimer *Timer2;
	TTimer *Timer3;
	TApplicationEvents *ApplicationEvents;
	TOpenPictureDialog *OpenPictureDialog;
	TAction *ATrace;
	TAction *ATraceBackground;
	TMenuItem *Trace1;
	TMenuItem *Background1;
	TAction *ATraceTool;
	TAction *AFileCloseAll;
	TMenuItem *CloseAll1;
	TAction *AFileChangeDim;
	TMenuItem *ChangeDim1;
	TMenuItem *N11;
	TGroupBox *GroupBoxLayersManager;
	TPanel *PanelLayersManager;
	TAction *AFileExportDAT;
	TGroupBox *GroupBoxEntities;
	TListBox *ListBoxEntities;
	TPanel *Panel2;
	TToolBar *ToolBar7;
	TToolButton *ToolButton13;
	TToolButton *ToolButton45;
	TAction *AEntityUp;
	TAction *AEntityDown;
	TPanel *Panel1;
	TSpeedButton *SpeedButton1;
	TAction *AEntitySwapEnds;
	TAction *AEntityBuildList;
	TToolButton *ToolButton46;
	TSplitter *Splitter1;
	TToolButton *ToolButton47;
	TToolButton *ToolButton48;
	TToolButton *ToolButton49;
	TToolButton *ToolButton50;
	TToolButton *ToolButton51;
	TToolButton *ToolButton54;
	TToolButton *ToolButton55;
	TAction *AEditJoin;
	TMenuItem *Join1;
	TToolButton *ToolButton56;
	TAction *AEditExplode;
	TMenuItem *Explode1;
	TToolButton *ToolButton57;
	TMenuItem *Line1;
	TToolButton *ToolButton58;
	TMainMenu *MainMenu2;
	TMenuItem *MenuItem1;
	TMenuItem *MenuItem2;
	TMenuItem *MenuItem3;
	TMenuItem *MenuItem4;
	TMenuItem *MenuItem5;
	TMenuItem *MenuItem6;
	TMenuItem *MenuItem7;
	TMenuItem *MenuItem8;
	TMenuItem *MenuItem9;
	TMenuItem *MenuItem10;
	TMenuItem *MenuItem11;
	TMenuItem *MenuItem12;
	TMenuItem *MenuItem13;
	TMenuItem *MenuItem14;
	TMenuItem *MenuItem15;
	TMenuItem *MenuItem16;
	TMenuItem *MenuItem17;
	TMenuItem *MenuItem18;
	TMenuItem *MenuItem19;
	TMenuItem *MenuItem20;
	TMenuItem *MenuItem21;
	TMenuItem *MenuItem22;
	TMenuItem *MenuItem23;
	TMenuItem *MenuItem24;
	TMenuItem *MenuItem25;
	TMenuItem *MenuItem26;
	TMenuItem *MenuItem27;
	TMenuItem *MenuItem28;
	TMenuItem *MenuItem29;
	TMenuItem *MenuItem30;
	TMenuItem *MenuItem31;
	TMenuItem *MenuItem32;
	TMenuItem *MenuItem33;
	TMenuItem *MenuItem34;
	TMenuItem *MenuItem35;
	TMenuItem *MenuItem36;
	TMenuItem *MenuItem37;
	TMenuItem *MenuItem38;
	TMenuItem *MenuItem39;
	TMenuItem *MenuItem40;
	TMenuItem *MenuItem41;
	TMenuItem *MenuItem42;
	TMenuItem *MenuItem43;
	TMenuItem *MenuItem44;
	TMenuItem *MenuItem45;
	TMenuItem *MenuItem46;
	TMenuItem *MenuItem47;
	TMenuItem *MenuItem48;
	TMenuItem *MenuItem49;
	TMenuItem *MenuItem50;
	TMenuItem *MenuItem51;
	TMenuItem *MenuItem52;
	TMenuItem *MenuItem53;
	TMenuItem *MenuItem54;
	TMenuItem *MenuItem55;
	TMenuItem *MenuItem56;
	TMenuItem *MenuItem57;
	TMenuItem *MenuItem58;
	TMenuItem *MenuItem59;
	TMenuItem *MenuItem60;
	TMenuItem *MenuItem61;
	TMenuItem *MenuItem62;
	TMenuItem *MenuItem63;
	TMenuItem *MenuItem64;
	TMenuItem *MenuItem65;
	TMenuItem *MenuItem66;
	TMenuItem *MenuItem67;
	TMenuItem *MenuItem68;
	TMenuItem *MenuItem69;
	TAction *AEntity;
	TMenuItem *Entity1;
	TMenuItem *Buildlist1;
	TMenuItem *Down1;
	TMenuItem *Swapends1;
	TMenuItem *Up1;
	TMenuItem *N10;
	TMenuItem *N12;
	TButton *Button1;
	void __fastcall FormCreate(TObject *Sender);
	void __fastcall FormDestroy(TObject *Sender);
	void __fastcall AFileExecute(TObject *Sender);
	void __fastcall AFileOpenExecute(TObject *Sender);
	void __fastcall AFileSaveExecute(TObject *Sender);
	void __fastcall AFileSaveAsExecute(TObject *Sender);
	void __fastcall AFileExitExecute(TObject *Sender);
	void __fastcall AZoomExecute(TObject *Sender);
	void __fastcall AZoomAllExecute(TObject *Sender);
	void __fastcall AZoomWindowExecute(TObject *Sender);
	void __fastcall AZoomInExecute(TObject *Sender);
	void __fastcall AZoomOutExecute(TObject *Sender);
	void __fastcall AZoomPanWindowExecute(TObject *Sender);
	void __fastcall ZoomToPrevExecute(TObject *Sender);
	void __fastcall AFileNewExecute(TObject *Sender);
	void __fastcall ASnapExecute(TObject *Sender);
	void __fastcall ASnapDlgExecute(TObject *Sender);
	void __fastcall ASnapGridExecute(TObject *Sender);
	void __fastcall ASnapPolarExecute(TObject *Sender);
	void __fastcall ASnapGripsExecute(TObject *Sender);
	void __fastcall ASnapPointExecute(TObject *Sender);
	void __fastcall ASnapNearExecute(TObject *Sender);
	void __fastcall ASnapEndExecute(TObject *Sender);
	void __fastcall ASnapMidExecute(TObject *Sender);
	void __fastcall ASnapCenterExecute(TObject *Sender);
	void __fastcall ASnapPerpendicularExecute(TObject *Sender);
	void __fastcall ASnapTangentExecute(TObject *Sender);
	void __fastcall PanelDisplayResize(TObject *Sender);
	void __fastcall AEditExecute(TObject *Sender);
	void __fastcall AEditEntPropExecute(TObject *Sender);
	void __fastcall AEditCopyExecute(TObject *Sender);
	void __fastcall AEditMoveExecute(TObject *Sender);
	void __fastcall AEditRotateExecute(TObject *Sender);
	void __fastcall AEditScaleExecute(TObject *Sender);
	void __fastcall AEditMirrorExecute(TObject *Sender);
	void __fastcall AEditEraseExecute(TObject *Sender);
	void __fastcall AEditUndoExecute(TObject *Sender);
	void __fastcall AEditRedoExecute(TObject *Sender);
	void __fastcall AEditCutCBExecute(TObject *Sender);
	void __fastcall AEditCopyCBExecute(TObject *Sender);
	void __fastcall AEditPasteCBExecute(TObject *Sender);
	void __fastcall AHelpExecute(TObject *Sender);
	void __fastcall AHelpContentsExecute(TObject *Sender);
	void __fastcall AHelpAboutExecute(TObject *Sender);
	void __fastcall AFileExportExecute(TObject *Sender);
	void __fastcall AFileImportExecute(TObject *Sender);
	void __fastcall ListBoxOpenedFilesClick(TObject *Sender);
	void __fastcall AFileCloseExecute(TObject *Sender);
	void __fastcall ADrawExecute(TObject *Sender);
	void __fastcall ADrawPolylineExecute(TObject *Sender);
	void __fastcall ADrawArcCSEExecute(TObject *Sender);
	void __fastcall ADrawArcSEMExecute(TObject *Sender);
	void __fastcall ADrawArcSMEExecute(TObject *Sender);
	void __fastcall ADrawCircleCRExecute(TObject *Sender);
	void __fastcall ADrawCircleCDExecute(TObject *Sender);
	void __fastcall ADrawCircle2PExecute(TObject *Sender);
	void __fastcall ADrawCircle3PExecute(TObject *Sender);
	void __fastcall ADrawEllipseExecute(TObject *Sender);
	void __fastcall ADrawLineExecute(TObject *Sender);
	void __fastcall ADrawRectangleExecute(TObject *Sender);
	void __fastcall AEditSetJumpExecute(TObject *Sender);
	void __fastcall AEditSetNormalExecute(TObject *Sender);
	void __fastcall AToolsExecute(TObject *Sender);
	void __fastcall AToolsSimulatorExecute(TObject *Sender);
	void __fastcall AToolsNavigatorExecute(TObject *Sender);
	void __fastcall Timer0Timer(TObject *Sender);
	void __fastcall Timer1Timer(TObject *Sender);
	void __fastcall Timer2Timer(TObject *Sender);
	void __fastcall Timer3Timer(TObject *Sender);
	void __fastcall ApplicationEventsActivate(TObject *Sender);
	void __fastcall ApplicationEventsDeactivate(TObject *Sender);
	void __fastcall ApplicationEventsMinimize(TObject *Sender);
	void __fastcall ApplicationEventsRestore(TObject *Sender);
	void __fastcall ActionList1Execute(TBasicAction *Action, bool &Handled);
	void __fastcall ATraceExecute(TObject *Sender);
	void __fastcall ATraceBackgroundExecute(TObject *Sender);
	void __fastcall ATraceToolExecute(TObject *Sender);
	void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
	void __fastcall AFileCloseAllExecute(TObject *Sender);
	void __fastcall AFileChangeDimExecute(TObject *Sender);
	void __fastcall AFileExportDATExecute(TObject *Sender);
	void __fastcall AEntityUpExecute(TObject *Sender);
	void __fastcall AEntityDownExecute(TObject *Sender);
	void __fastcall ListBoxEntitiesClick(TObject *Sender);
	void __fastcall AEntitySwapEndsExecute(TObject *Sender);
	void __fastcall AEntityBuildListExecute(TObject *Sender);
	void __fastcall FormKeyDown(TObject *Sender, WORD &Key,
          TShiftState Shift);
	void __fastcall AEditJoinExecute(TObject *Sender);
	void __fastcall AEditExplodeExecute(TObject *Sender);
	void __fastcall AEntityExecute(TObject *Sender);
	void __fastcall Button1Click(TObject *Sender);
private:	// User declarations
public:		// User declarations
	__fastcall TFormMain(TComponent* Owner);
	void __fastcall DrawQuiltingFile(AnsiString strFileName);
	void __fastcall NewDocument(AnsiString strFileName,int nWidth,int nHeight);
	void __fastcall OpenDATFile(AnsiString strFileName);
	void __fastcall ExtractLayers(ql_Layers &Layers);
	void __fastcall SaveDATFile(AnsiString strFileName);
	void __fastcall BuildEntitiesList();
	void __fastcall ActivateDesigner();
	void __fastcall Draw(int EntityIndex);
	void __fastcall SwapEnds(int EntityIndex);
	void __fastcall DrawQuiltingArc(ql_Stitch &QuiltingStitch);
	void __fastcall OnSelectEntity();
	void __fastcall OnUnSelectEntity();
	void __fastcall EnableActions(bool bValue);
	void __fastcall ScaleDrawing();
    HWND ghwVec;   // VeCAD window to display draw
    int  SBarH;    // height of status bar
    AnsiString m_strFileName;
    bool TheEnd;

    ql_File QuiltingFile;

    int m_nDotLineStyleIndex;
    int m_nSoildLineStyleIndex;

    AnsiString m_strAppTitle;
	int m_nIndex;

    TCanvas *m_pCanvas;

    int m_nWorkingAreaRectIndex;
    int m_nImageIndex;
    int m_nBackgroundLayer;
    int m_nDrawingLayer;
    AnsiString strImageName;

    int m_nItemIndex;

    info_SystemInfo *m_pSystemInfo;
};
//---------------------------------------------------------------------------
extern PACKAGE TFormMain *FormMain;
//---------------------------------------------------------------------------
#endif
